select_origin: directory
files_origin: "./fiches"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  économie:
    fill: "#4E7AC7"
    stroke: "#4E7AC7"
  social:
    fill: "#E67E22"
    stroke: "#E67E22"
  agriculture et écologie:
    fill: "#006400"
    stroke: "#006400"
  culture et sport:
    fill: "#C0392B"
    stroke: "#C0392B"
  communication:
    fill: "#F1C40F"
    stroke: "#F1C40F"
  administration:
    fill: "#2ECC71"
    stroke: "#2ECC71"
  éducation:
    fill: "#2ECC78"
    stroke: "#2ECC78"
  undefined:
    fill: "#858585"
    stroke: "#858585"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: "Missions du conseil départemental de Gironde"
author: "BUT 3 Infonum"
description: ""
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: "./gironde.css"
devtools: false
lang: en
