select_origin: directory
files_origin: ./fiches
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
      fill: "#858585"
      stroke: "#858585"
  personne:
      fill: "#FF0000"
      stroke: "#FF0000"
  organisme public:
      fill: "#00FF00"
      stroke: "#00FF00"
  organisme privé:
      fill: "#0000FF"
      stroke: "#0000FF"
  scientifique:
      fill: "#FFFF00"
      stroke: "#FFFF00"
  géographique:
      fill: "#00FFFF"
      stroke: "#00FFFF"  
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
chronological_record_meta: created
record_metas:
  - links
  - short
title: ""
author: ""
description: ""
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: fr
name: ""
