remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
links:
  - title: Projet Open Data Sphère
    url: /documentation.html
  - title: Guide ODS
    url: /guidedenavigation.html
  